In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [5]:
df = pd.read_csv(r"C:\Users\dellf\OneDrive\Desktop\apple_quality.csv")
df.head(5)


A_id      Size    Weight  Sweetness  Crunchiness  Juiciness  Ripeness  \
0   0.0 -3.970049 -2.512336   5.346330    -1.012009   1.844900  0.329840   
1   1.0 -1.195217 -2.839257   3.664059     1.588232   0.853286  0.867530   
2   2.0 -0.292024 -1.351282  -1.738429    -0.342616   2.838636 -0.038033   
3   3.0 -0.657196 -2.271627   1.324874    -0.097875   3.637970 -3.413761   
4   4.0  1.364217 -1.296612  -0.384658    -0.553006   3.030874 -1.303849   

        Acidity Quality  
0  -0.491590483    good  
1  -0.722809367    good  
2   2.621636473     bad  
3   0.790723217    good  
4   0.501984036    good

In [6]:
Size = np.array([-3.970049, -1.195217, -0.292024, -0.657196, 1.364217]).reshape((-1, 1))
Weight = np.array([-2.512336, -2.839257, -1.351282, -2.271627, -1.296612])

In [7]:
import numpy as np

Size = np.array([[-3.970049],
                [-1.195217],
                [-0.292024],
                [-0.657196],
                [1.364217]])

Weight = np.array([-2.512336, -2.839257, -1.351282, -2.271627, -1.296612])

In [8]:
model = LinearRegression()

In [9]:
model.fit(Size, Weight)
LinearRegression()

LinearRegression()

In [10]:
model = LinearRegression().fit(Size, Weight)

In [11]:
model = LinearRegression().fit(Size, Weight)

In [12]:
r_sq = model.score(Size, Weight)
print(f"coefficient of determination: {r_sq}")

coefficient of determination: 0.4755180293771335


In [13]:
print(f"intercept: {model.intercept_}")


print(f"slope: {model.coef_}")

intercept: -1.818956421078599
slope: [0.2476348]


In [14]:
new_model = LinearRegression().fit(Size, Weight.reshape((-1, 1)))
print(f"intercept: {new_model.intercept_}")


print(f"slope: {new_model.coef_}")

intercept: [-1.81895642]
slope: [[0.2476348]]


In [15]:
Weight_pred = model.predict(Size)
print(f"predicted response:\n{Weight_pred}")

predicted response:
[-2.8020787  -2.11493374 -1.89127172 -1.98170102 -1.48112882]


In [16]:
Weight_pred = model.intercept_ + model.coef_ * Size
print(f"predicted response:\n{Weight_pred}")

predicted response:
[[-2.8020787 ]
 [-2.11493374]
 [-1.89127172]
 [-1.98170102]
 [-1.48112882]]


In [17]:
Size_new = np.arange(5).reshape((-1, 1))
Size_new






Weight_new = model.predict(Size_new)
Weight_new

array([-1.81895642, -1.57132163, -1.32368683, -1.07605203, -0.82841724])

In [18]:
import numpy as np
from sklearn.linear_model import LinearRegression

Size = [
  [0, 1], [5, 1], [15, 2], [25, 5], [35, 11], [45, 15], [55, 34], [60, 35]
]
Weight = [4, 5, 20, 14, 32, 22, 38, 43]
Size, Weight = np.array(Size), np.array(Weight)

In [20]:
from sklearn.preprocessing import PolynomialFeatures

transformer = PolynomialFeatures(degree=2, include_bias=False)


In [21]:
transformer.fit(Size)

PolynomialFeatures(include_bias=False)

In [22]:
Size_ = transformer.transform(Size)

In [23]:
Size_ = PolynomialFeatures(degree=2, include_bias=False).fit_transform(Size)

In [24]:
import numpy as np

Size_ = np.array([[-3.970049, -1.195217],
                [-1.195217, 1.364217],
                [-0.292024, -0.657196],
                [-0.657196, -0.657196]])

In [25]:
model = LinearRegression().fit(Size, Weight)

In [26]:
Size_ = PolynomialFeatures(degree=2, include_bias=True).fit_transform(Size)

In [27]:
model = LinearRegression(fit_intercept=False).fit(Size_, Weight)

In [28]:
r_sq = model.score(Size_, Weight)
print(f"coefficient of determination: {r_sq}")


print(f"intercept: {model.intercept_}")


print(f"coefficients: {model.coef_}")

coefficient of determination: 0.9453701449127823
intercept: 0.0
coefficients: [ 0.84305565  2.44828275  0.16160353 -0.15259677  0.47928683 -0.4641851 ]


In [29]:
Weight_pred = model.predict(Size_)
print(f"predicted response:\n{Weight_pred}")

predicted response:
[ 0.54047408 11.36340283 16.07809622 15.79139    29.73858619 23.50834636
 39.05631386 41.92339046]


In [30]:
# Step 1: Import packages and classes
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

# Step 2a: Provide data
Size = [
  [0, 1], [5, 1], [15, 2], [25, 5], [35, 11], [45, 15], [55, 34], [60, 35]
]
Weight = [4, 5, 20, 14, 32, 22, 38, 43]
Size, Weight = np.array(Size), np.array(Weight)

# Step 2b: Transform input data
Size_ = PolynomialFeatures(degree=2, include_bias=False).fit_transform(Size)

# Step 3: Create a model and fit it
model = LinearRegression().fit(Size_, Weight)

# Step 4: Get results
r_sq = model.score(Size_, Weight)
intercept, coefficients = model.intercept_, model.coef_

# Step 5: Predict response
Weight_pred = model.predict(Size_)

In [31]:
print(f"coefficient of determination: {r_sq}")


print(f"intercept: {intercept}")


print(f"coefficients:\n{coefficients}")



print(f"predicted response:\n{Weight_pred}")

coefficient of determination: 0.945370144912782
intercept: 0.8430556452396445
coefficients:
[ 2.44828275  0.16160353 -0.15259677  0.47928683 -0.4641851 ]
predicted response:
[ 0.54047408 11.36340283 16.07809622 15.79139    29.73858619 23.50834636
 39.05631386 41.92339046]


In [32]:
import numpy as np
import statsmodels.api as sm

In [33]:
Size = [
  [0, 1], [5, 1], [15, 2], [25, 5], [35, 11], [45, 15], [55, 34], [60, 35]
]
Weight = [4, 5, 20, 14, 32, 22, 38, 43]
Size, Weight = np.array(Size), np.array(Weight)

In [34]:
Size = sm.add_constant(Size)

In [35]:
model = sm.OLS(Weight, Size)

In [36]:
results = model.fit()

In [37]:
print(results.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.862
Model:                            OLS   Adj. R-squared:                  0.806
Method:                 Least Squares   F-statistic:                     15.56
Date:                Tue, 12 Mar 2024   Prob (F-statistic):            0.00713
Time:                        20:36:51   Log-Likelihood:                -24.316
No. Observations:                   8   AIC:                             54.63
Df Residuals:                       5   BIC:                             54.87
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          5.5226      4.431      1.246      0.2

c:\Users\dellf\anaconda\lib\site-packages\scipy\stats\_stats_py.py:1736: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=8
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "


In [38]:
print(f"coefficient of determination: {results.rsquared}")


print(f"adjusted coefficient of determination: {results.rsquared_adj}")


print(f"regression coefficients: {results.params}")

coefficient of determination: 0.8615939258756776
adjusted coefficient of determination: 0.8062314962259487
regression coefficients: [5.52257928 0.44706965 0.25502548]


In [39]:
print(f"predicted response:\n{results.fittedvalues}")




print(f"predicted response:\n{results.predict(Size)}")

predicted response:
[ 5.77760476  8.012953   12.73867497 17.9744479  23.97529728 29.4660957
 38.78227633 41.27265006]
predicted response:
[ 5.77760476  8.012953   12.73867497 17.9744479  23.97529728 29.4660957
 38.78227633 41.27265006]


In [40]:
Size_new = sm.add_constant(np.arange(10).reshape((-1, 2)))
Size_new






Weight_new = results.predict(Size_new)
Weight_new

array([ 5.77760476,  7.18179502,  8.58598528,  9.99017554, 11.3943658 ])